# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-07 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gatech_research_central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='last_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='study',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 6, 21, 27, 31, 545332)),
        ),
    ]
