# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-23 02:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gatech_research_central', '0002_auto_20170107_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='study',
            name='last_date',
            field=models.DateField(default=datetime.datetime(2017, 2, 22, 2, 9, 17, 718648)),
        ),
        migrations.AlterField(
            model_name='study',
            name='text',
            field=models.TextField(help_text=b'eg. Our study goes on till the 30th. Visit http://doodle.com for more information'),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(help_text=b'eg. Robotics study', max_length=200),
        ),
    ]
